### ISSUE TITLE
Commission a mascot

### ISSUE THREAD

**Issue by krainboltgreene** [lacqueristas/tasks#32]
Here are is the rough outline of the mascot:

  1. The mascot is a Llama.
  2. The mascot's aesthetic could be "super cute" or bubbly (So not overly realistic, but recognizable)
  3. Further details:
    1. The Llama will be "femme", but not overtly so. A gender identity can be assumed, but not directly expressed (No pink bows, for example).
    2. The Llama isn't required to have any clothing.
    3. The Llama shouldn't be anthropomorphic or humanoid.
    4. The Llama should have painted "nails" (abstracted so they don't actually need humanoid nails, but implied)

The llama will reflect the attitude amongst the community (llamas being pack animals and very smug looking).

**Comment by krainboltgreene** [comment]
It's time to purchase the commissions, but I'm wavering on what animal after talking to friends. Here's the latest email to the artist:

> Hey Nico,
> 
> Sorry this email is late, been working on deploying the server.
> 
> So here's what I'd like you to do for this commission set:
> 
> I'd like a set of sketches, flat color, experimenting with the details in our previous correspondence email, however I want to break this into three pieces:
> 
>   1. The llama, as originally described
>   2. A lemur (equally as cute and also ringed tail == nail polish?)
>   3. A lorikeet, see: https://en.wikipedia.org/wiki/Lories_and_lorikeets
> 
> I don't know how many sketches you feel this would require to explore each topic, but I think for the first iteration I'd like to pay $100 up front as I described before.
> 
> Let me know if these are feasible! If I can get these done I'll probably move on to a specific animal, hopefully commissioning you for a significantly more detailed version of the "winner".
> 
> Cheers

**Comment by krainboltgreene** [comment]
First batch:

![lacquerista lemur](https://cloud.githubusercontent.com/assets/334809/14405911/1787ba94-fe4f-11e5-9d73-0bb4ff1c163a.png)
![llama lacquerista](https://cloud.githubusercontent.com/assets/334809/14405913/178f6424-fe4f-11e5-9e15-e23cb7688fc4.png)
![lorikeet lacquerista](https://cloud.githubusercontent.com/assets/334809/14405912/178ceece-fe4f-11e5-9d87-b0ba7bc3bd2c.png)

**Comment by krainboltgreene** [comment]
Refining the llama:

![llama1](https://cloud.githubusercontent.com/assets/334809/14405919/3cb7bd5a-fe4f-11e5-976f-64c37c1d0cf0.png)
![llama2](https://cloud.githubusercontent.com/assets/334809/14405920/3cbb43da-fe4f-11e5-8214-68ed143b7c1e.png)
![llama3](https://cloud.githubusercontent.com/assets/334809/14405922/3cbe9f80-fe4f-11e5-84e5-17dbd923c58a.png)
![llama4](https://cloud.githubusercontent.com/assets/334809/14405921/3cbe686c-fe4f-11e5-92bb-c3103cc7cf5e.png)

**Comment by quephird** [comment]
😻😻😻

**Comment by krainboltgreene** [comment]
We got a color pallet to work with:

![llama palette](https://cloud.githubusercontent.com/assets/334809/14576426/cfa221f0-031d-11e6-8951-05c618cf9462.png)

**Comment by krainboltgreene** [comment]
Final sketches are in!

![llama5](https://cloud.githubusercontent.com/assets/334809/14590350/cf8aaed6-04ac-11e6-84c7-cd7b11bf139c.png)
![llama6](https://cloud.githubusercontent.com/assets/334809/14590348/cc5ec1a2-04ac-11e6-9d50-d7aa1e0377c4.png)
![llama7](https://cloud.githubusercontent.com/assets/334809/14590349/cdeaebb8-04ac-11e6-9975-093201b3f4da.png)

**Comment by quephird** [comment]
Gosh, those are _amazing_.

**Comment by krainboltgreene** [comment]
@quephird Right?! Now it's time to move on to copy and narrative. Already have a freelancer lined up.
